name: Checks

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Yarn
        run: npm i --global yarn@1

      - name: Install/Build
        run: |
          yarn
          yarn build:libs

      - name: Typecheck
        run: yarn typecheck:all
